# Generated by Django 4.2.7 on 2025-11-20 11:11

import apparel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApparelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product name/title', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('image', models.ImageField(help_text='Upload product image (JPG, PNG)', upload_to=apparel.models.apparel_image_upload_path)),
                ('category', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DEFAULT', 'Default'), ('ALL', 'All')], default='ALL', help_text='Target audience category', max_length=10)),
                ('sizes', models.JSONField(default=list, help_text='Available sizes (S, M, L, XL, XXL)')),
                ('mrp_price', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available Now'), ('CUSTOM', 'Custom Order'), ('ORDER', 'Made to Order')], default='AVAILABLE', help_text='Product availability status', max_length=10)),
                ('whatsapp_message', models.TextField(blank=True, help_text='Pre-filled WhatsApp message for orders')),
                ('is_active', models.BooleanField(default=True, help_text='Display this product on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apparel Product',
                'verbose_name_plural': 'Apparel Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
