# Generated by Django 4.2.7 on 2025-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparelproduct',
            name='category',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', help_text='Target audience category', max_length=10),
        ),
        migrations.AlterField(
            model_name='apparelproduct',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available Now'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', help_text='Product availability status', max_length=15),
        ),
    ]
