# Generated by Django 4.2.7 on 2025-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_alter_apparelproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Unique order ID', max_length=50, unique=True)),
                ('product_title', models.CharField(help_text='Product name', max_length=200)),
                ('size', models.CharField(help_text='Product size', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Order quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price in INR', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (price × quantity)', max_digits=10)),
                ('full_name', models.CharField(help_text='Customer full name', max_length=200)),
                ('mobile', models.CharField(help_text='Customer mobile number', max_length=15)),
                ('country_code', models.CharField(default='+91', help_text='Country code', max_length=5)),
                ('house_flat_no', models.CharField(help_text='House/Flat number', max_length=200)),
                ('street_locality', models.CharField(help_text='Street/Locality', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('pin_code', models.CharField(help_text='PIN code', max_length=10)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='COD', help_text='Payment mode', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=15)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Order processing status', max_length=15)),
                ('whatsapp_message_sid', models.CharField(blank=True, help_text='Twilio WhatsApp message SID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
